// <auto-generated />
using System;
using ChoreDataModel.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ChoreServiceBusHost.Migrations
{
    [DbContext(typeof(ChoreContext))]
    [Migration("20200516182823_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0-preview.3.20181.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ChoreDataModel.Model.Chore", b =>
                {
                    b.Property<int>("ChoreID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Assigned")
                        .HasColumnType("bit");

                    b.Property<int>("AssignedPartnerId")
                        .HasColumnType("int");

                    b.Property<string>("ChoreName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ChoreSprintId")
                        .HasColumnType("int");

                    b.Property<bool>("Completed")
                        .HasColumnType("bit");

                    b.Property<int?>("PartnerId")
                        .HasColumnType("int");

                    b.HasKey("ChoreID");

                    b.HasIndex("ChoreSprintId");

                    b.HasIndex("PartnerId");

                    b.ToTable("Chores");
                });

            modelBuilder.Entity("ChoreDataModel.Model.ChoreSprint", b =>
                {
                    b.Property<int>("ChoreSprintId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTimeOffset>("EndDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("StartDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("ChoreSprintId");

                    b.ToTable("ChoreSprints");
                });

            modelBuilder.Entity("ChoreDataModel.Model.Partner", b =>
                {
                    b.Property<int>("PartnerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CompletedChores")
                        .HasColumnType("int");

                    b.Property<int>("IncompleteChores")
                        .HasColumnType("int");

                    b.Property<string>("PartnerName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PartnerId");

                    b.ToTable("Partners");
                });

            modelBuilder.Entity("ChoreDataModel.Model.Chore", b =>
                {
                    b.HasOne("ChoreDataModel.Model.ChoreSprint", null)
                        .WithMany("Chores")
                        .HasForeignKey("ChoreSprintId");

                    b.HasOne("ChoreDataModel.Model.Partner", null)
                        .WithMany("Chores")
                        .HasForeignKey("PartnerId");
                });
#pragma warning restore 612, 618
        }
    }
}
